// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoEventos.Data;

#nullable disable

namespace ProjetoEventos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502122457_primeira")]
    partial class primeira
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjetoEventos.Models.Certificado", b =>
                {
                    b.Property<int>("CertificadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CertificadoId"));

                    b.Property<DateOnly>("Data_emissao")
                        .HasColumnType("date");

                    b.Property<int>("InscricaoId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.HasKey("CertificadoId");

                    b.HasIndex("InscricaoId");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<DateOnly>("Data_evento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("PatrocinadorId")
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.HasKey("EventoId");

                    b.HasIndex("PatrocinadorId");

                    b.HasIndex("TipoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Inscricao", b =>
                {
                    b.Property<int>("InscricaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InscricaoId"));

                    b.Property<DateOnly>("Data_inscricao")
                        .HasColumnType("date");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("int");

                    b.HasKey("InscricaoId");

                    b.HasIndex("EventoId");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("Inscricao");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Participante", b =>
                {
                    b.Property<int>("ParticipanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParticipanteId"));

                    b.Property<string>("Celular")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Perfil_profissionalId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ParticipanteId");

                    b.HasIndex("Perfil_profissionalId");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Patrocinador", b =>
                {
                    b.Property<int>("PatrocinadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatrocinadorId"));

                    b.Property<string>("Nome_empresa")
                        .HasColumnType("longtext");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("PatrocinadorId");

                    b.ToTable("Patrocinadores");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Perfil_profissional", b =>
                {
                    b.Property<int>("Perfil_profissionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Perfil_profissionalId"));

                    b.Property<string>("Descritivo")
                        .HasColumnType("longtext");

                    b.Property<string>("Linkdinurl")
                        .HasColumnType("longtext");

                    b.HasKey("Perfil_profissionalId");

                    b.ToTable("Perfis_profissionais");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Tipo", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<string>("Descritivo")
                        .HasColumnType("longtext");

                    b.HasKey("TipoId");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Certificado", b =>
                {
                    b.HasOne("ProjetoEventos.Models.Inscricao", "Inscricao")
                        .WithMany()
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscricao");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Evento", b =>
                {
                    b.HasOne("ProjetoEventos.Models.Patrocinador", "Patrocinador")
                        .WithMany("Evento")
                        .HasForeignKey("PatrocinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEventos.Models.Tipo", "Tipo")
                        .WithMany("Evento")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patrocinador");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Inscricao", b =>
                {
                    b.HasOne("ProjetoEventos.Models.Evento", "Evento")
                        .WithMany("Inscricao")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEventos.Models.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Participante", b =>
                {
                    b.HasOne("ProjetoEventos.Models.Perfil_profissional", "Perfil_profissional")
                        .WithMany()
                        .HasForeignKey("Perfil_profissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil_profissional");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Evento", b =>
                {
                    b.Navigation("Inscricao");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Patrocinador", b =>
                {
                    b.Navigation("Evento");
                });

            modelBuilder.Entity("ProjetoEventos.Models.Tipo", b =>
                {
                    b.Navigation("Evento");
                });
#pragma warning restore 612, 618
        }
    }
}
